name: Build and Run Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install googletest
      - name: Install googletest
        uses: cvpkg/googletest-action@v0.1
        with:
          googletest_tag: 'release-1.11.0'

      # Install Clang-Tidy
      - name: Install Clang-Tidy
        run: sudo apt-get install -y clang-tidy

      # Run Clang-Tidy for linting C++ code
      - name: Run Clang-Tidy
        run: |
          clang-tidy src/*.c -- -Iinclude

      # Create input file for testing
      - name: Create input file
        run: |
          touch input.txt
          echo "Hello World" > input.txt
          echo "This is a test" >> input.txt
          echo "GoogleTest Example" >> input.txt
          echo "Remove vowels please" >> input.txt
          echo "Another random string" >> input.txt
          echo "Some more text" >> input.txt
          echo "Just a string" >> input.txt
          echo "Final line" >> input.txt

      # Create output files
      - name: Create output files
        run: |
          touch output1.txt
          touch output2.txt

      # Build project
      - name: Build Project
        run: |
          cmake -S . -B build
          cmake --build build

      # Run tests with process check
      - name: Run tests in background
        run: |
          cd build
          ./test &
          sleep 30
          ps aux

      # Check if output files exist
      - name: Check if output files exist
        run: |
          ls -l build/output1.txt
          ls -l build/output2.txt

      # Print contents of the output files
      - name: Print output file contents
        run: |
          echo "Contents of output1.txt:"
          cat build/output1.txt
          echo " "
          echo "Contents of output2.txt:"
          cat build/output2.txt

      # Remove output files
      - name: Remove output files
        run: |
          rm -f output1.txt
          rm -f output2.txt
