name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install cmake g++

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build
          ./main  # Выполнение тестов

      - name: Check if output files exist
        run: |
          ls -l output1.txt
          ls -l output2.txt
